# Generated by Django 2.2 on 2023-01-27 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_post_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='post',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
